name: Test

on: [push, pull_request]

permissions: read-all

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
      - name: Scarb version
        run: scarb --version
      - name: Check cairo format
        run: scarb fmt --check
      - name: Build cairo programs
        run: scarb build
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
      - name: Scarb version
        run: scarb --version
      - uses: actions/checkout@v3
      - uses: foundry-rs/setup-snfoundry@v3
        with:
          starknet-foundry-version: "0.23.0"
      - name: Run cairo tests
        run: snforge test
